export const ACHIEVEMENTS_DATA = [
  {
    achievementId: 'FIRST_BLOOD',
    name: 'FIRST BLOOD',
    description: 'Win your first battle in the arena.',
    icon: '🩸',
    rarity: 'COMMON' as const,
    xpReward: 100,
    category: 'combat',
    requirements: { type: 'firstWin', value: 1, description: 'Win 1 battle' },
  },
  {
    achievementId: 'TEN_WINS',
    name: 'TEN WINS',
    description: 'Achieve 10 victories in battle.',
    icon: '⚔️',
    rarity: 'UNCOMMON' as const,
    xpReward: 250,
    category: 'combat',
    requirements: { type: 'wins', value: 10, description: 'Win 10 battles' },
  },
  {
    achievementId: 'FIFTY_WINS',
    name: 'BATTLE HARDENED',
    description: 'Accumulate 50 battle victories.',
    icon: '🗡️',
    rarity: 'RARE' as const,
    xpReward: 500,
    category: 'combat',
    requirements: { type: 'wins', value: 50, description: 'Win 50 battles' },
  },
  {
    achievementId: 'HUNDRED_WINS',
    name: 'ARENA KING',
    description: '100 victories. The arena bows to you.',
    icon: '👑',
    rarity: 'EPIC' as const,
    xpReward: 1000,
    category: 'combat',
    requirements: { type: 'wins', value: 100, description: 'Win 100 battles' },
  },
  {
    achievementId: 'WIN_STREAK_3',
    name: 'ON FIRE',
    description: 'Win 3 battles in a row.',
    icon: '🔥',
    rarity: 'COMMON' as const,
    xpReward: 150,
    category: 'streak',
    requirements: { type: 'winStreak', value: 3, description: '3-win streak' },
  },
  {
    achievementId: 'WIN_STREAK_5',
    name: 'UNSTOPPABLE',
    description: '5-win streak. Pure dominance.',
    icon: '⚡',
    rarity: 'UNCOMMON' as const,
    xpReward: 300,
    category: 'streak',
    requirements: { type: 'winStreak', value: 5, description: '5-win streak' },
  },
  {
    achievementId: 'WIN_STREAK_10',
    name: 'GODLIKE',
    description: '10-win streak. You are unreachable.',
    icon: '🌟',
    rarity: 'LEGENDARY' as const,
    xpReward: 1500,
    category: 'streak',
    requirements: { type: 'bestWinStreak', value: 10, description: '10-win streak' },
  },
  {
    achievementId: 'WHALE_SLAYER',
    name: 'WHALE SLAYER',
    description: 'Defeat a Whale archetype warrior.',
    icon: '🐋',
    rarity: 'RARE' as const,
    xpReward: 500,
    category: 'special',
    requirements: { type: 'defeat_whale', value: 1, description: 'Defeat a Whale' },
  },
  {
    achievementId: 'CRITICAL_MASTER',
    name: 'CRITICAL MASTER',
    description: 'Land 3 critical hits in a single battle.',
    icon: '💥',
    rarity: 'RARE' as const,
    xpReward: 400,
    category: 'combat',
    requirements: { type: 'critical_hits_battle', value: 3, description: '3 crits in one battle' },
  },
  {
    achievementId: 'UNTOUCHABLE',
    name: 'UNTOUCHABLE',
    description: 'Win a battle without your opponent landing a single hit.',
    icon: '🛡️',
    rarity: 'EPIC' as const,
    xpReward: 750,
    category: 'defense',
    requirements: { type: 'perfect_win', value: 1, description: 'Perfect win' },
  },
  {
    achievementId: 'LEVEL_10',
    name: 'SEASONED WARRIOR',
    description: 'Reach Level 10.',
    icon: '📈',
    rarity: 'UNCOMMON' as const,
    xpReward: 300,
    category: 'progression',
    requirements: { type: 'level', value: 10, description: 'Reach Level 10' },
  },
  {
    achievementId: 'LEVEL_25',
    name: 'ELITE',
    description: 'Reach Level 25.',
    icon: '💎',
    rarity: 'RARE' as const,
    xpReward: 750,
    category: 'progression',
    requirements: { type: 'level', value: 25, description: 'Reach Level 25' },
  },
  {
    achievementId: 'LEVEL_50',
    name: 'LEGEND',
    description: 'Reach Level 50. You are a legend of the arena.',
    icon: '🔱',
    rarity: 'LEGENDARY' as const,
    xpReward: 2500,
    category: 'progression',
    requirements: { type: 'level', value: 50, description: 'Reach Level 50' },
  },
  {
    achievementId: 'TOTAL_BATTLES_10',
    name: 'BATTLE TESTED',
    description: 'Participate in 10 battles.',
    icon: '⚔️',
    rarity: 'COMMON' as const,
    xpReward: 100,
    category: 'participation',
    requirements: { type: 'total_battles', value: 10, description: 'Fight 10 battles' },
  },
  {
    achievementId: 'TOTAL_BATTLES_50',
    name: 'ARENA VETERAN',
    description: 'Participate in 50 battles.',
    icon: '🎖️',
    rarity: 'UNCOMMON' as const,
    xpReward: 400,
    category: 'participation',
    requirements: { type: 'total_battles', value: 50, description: 'Fight 50 battles' },
  },
  {
    achievementId: 'WIN_STREAK_20',
    name: 'INVINCIBLE',
    description: '20-win streak. You cannot be stopped.',
    icon: '⭐',
    rarity: 'LEGENDARY' as const,
    xpReward: 3000,
    category: 'streak',
    requirements: { type: 'bestWinStreak', value: 20, description: '20-win streak' },
  },
  {
    achievementId: 'TOTAL_BATTLES_100',
    name: 'ARENA MASTER',
    description: 'Participate in 100 battles.',
    icon: '🏟️',
    rarity: 'RARE' as const,
    xpReward: 800,
    category: 'participation',
    requirements: { type: 'total_battles', value: 100, description: 'Fight 100 battles' },
  },
  {
    achievementId: 'FIVE_HUNDRED_WINS',
    name: 'CHAMPION',
    description: '500 victories. You own the arena.',
    icon: '🏆',
    rarity: 'LEGENDARY' as const,
    xpReward: 5000,
    category: 'combat',
    requirements: { type: 'wins', value: 500, description: 'Win 500 battles' },
  },
  {
    achievementId: 'TWENTY_FIVE_WINS',
    name: 'RISING STAR',
    description: 'Achieve 25 victories.',
    icon: '🌠',
    rarity: 'UNCOMMON' as const,
    xpReward: 350,
    category: 'combat',
    requirements: { type: 'wins', value: 25, description: 'Win 25 battles' },
  },
  {
    achievementId: 'WIN_STREAK_7',
    name: 'RELENTLESS',
    description: '7-win streak. Relentless in the arena.',
    icon: '🔱',
    rarity: 'RARE' as const,
    xpReward: 600,
    category: 'streak',
    requirements: { type: 'bestWinStreak', value: 7, description: '7-win streak' },
  },
];
